name: test3
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  animated_theme_switcher: ^2.0.7
  animations: ^2.0.7
  animator: ^3.2.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  font_awesome_flutter: ^10.2.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  http: ^0.13.5
  injectable: ^1.5.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  path_provider: ^2.0.11
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.15
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  hive_generator: ^2.0.0
  injectable_generator: ^1.5.3

flutter:
  uses-material-design: true
  assets:
  # - assets/images/
  - assets/animations/
